### ISSUE TITLE
Elements can not be deleted

### ISSUE THREAD

**Issue by d70-t** [ory/editor#345]
After inserting and moving lots of elements on the landing page (http://editor.ory.am/) no element can be deleted any more. Due to #344 the modified layout has been lost.

**Comment by arekkas** [comment]
I checked our sentry logs and was not able to find anything. Unfortunately, without a reproducible case there is not a lot I can do :(

If you encounter the issue again, feel free to reopen this!

**Comment by inyono** [comment]
He did some pretty weird stuff and had a rather deeply nested layout 😁
