### ISSUE TITLE
Demo is broken in Edge

### ISSUE THREAD

**Issue by nozzlegear** [ory/editor#390]
Hey! I was trying to use the demo in MS Edge, but got this error in the console:

![image](https://cloud.githubusercontent.com/assets/2417276/26464412/57614e2c-414d-11e7-809b-daa003c05560.png)

Which leaves the demo page looking like this: 

![image](https://cloud.githubusercontent.com/assets/2417276/26464435/67ff6f52-414d-11e7-8d35-e3ec78911f62.png)

**Comment by arekkas** [comment]
Thanks for reporting this, this is most likely due to a missing polyfill - I'll investigate that soon!

**Comment by pierreneter** [comment]
Fixed it with: #409
