### ISSUE TITLE
Supporting Multiple Instances

### ISSUE THREAD

**Issue by brobertsUPS** [ory/editor#393]
Are there plans to support multiple instances of the editor? There is a warning in the core package source [here](https://github.com/ory/editor/blob/c22ec38e9da1efb668e294e2087856fdc67cf1f9/packages/core/src/index.js) : "You have defined multiple instances of Editor, this could cause problems".

My use case is to have a component paired with the Editor and have many of those components within my page.

EX: 

```
const plugins = {
  content: [slate()], // Define plugins for content cells
  layout: [parallax({ defaultPlugin: slate() })] // Define plugins for layout cells
};
const content = createEmptyState();
const editor = new Editor({
  plugins,
  // pass the content state - you can add multiple editables here
  editables: [content]
});

const TextboxAppContainer = () => (
	<div className="ory">
	    <Editable editor={editor} id={content.id}/>
        <Trash editor={editor}/>
        <DisplayModeToggle editor={editor}/>
        <Toolbar editor={editor}/>
	</div>
);
```

I would expect to render TextboxAppContainer in multiple places on the page and have them act independently.

**Comment by arekkas** [comment]
Hey, you can have multiple editables on one page (check the demo), but only one instance :) So yes, this is possible to some extent!

**Comment by brobertsUPS** [comment]
@arekkas Thanks a ton! That definitely makes sense for the design of Ory. Keep up the awesome work!

**Comment by arekkas** [comment]
Just to be clear, each editable is it's own editor if you will, so you only have one instance of the `Editor` class, but you can have multiple regions in a page that have an editor and are separate from one another

**Comment by brobertsUPS** [comment]
@arekkas Your explanation was clear. I have switched to using slate project itself which suits my needs better.

**Comment by davidpelayo** [comment]
Does it mean that, for some reason, you can't have two different versions of the editor loaded at the same time?

**Comment by arekkas** [comment]
What would be a use case for having two different versions?

**Comment by davidpelayo** [comment]
Just guessing (not an actual case to me so far). Imagine you have your app on production running and you need to support a specific legacy version, while wanting to upgrade to latest on a new page of your SPA just developed? Both, packed with webpack on the same bundle. Does it make sense?

**Comment by bkniffler** [comment]
I find this a bit confusing. Why not architect this differently with an editor provider HOC injecting the editor instance to context and the editables using the context? I know this could easily be build on top of ory, but in my opinion it should be the default. Also, why is the content part of the editor instance instead of the editable component? And why is it called editor instance anyways, wouldn't it be better to call it EditorConfiguration or something like that?

Sorry in case I'm missing something and sorry about being a bit off topic..

**Comment by arekkas** [comment]
We need one redux store which is global - that is required because we might want to drop things from one editable to another editable. The editor instance is primarily responsible for instantiating and carrying this redux store.

This is the primary reason why we have one instance.

**Comment by arekkas** [comment]
@davidpelayo sorry I totally missed your comment. I'm not sure how that would work as you can't load two different versions from npm nor import two different versions of the same package.

**Comment by bkniffler** [comment]
Thanks for the explanation @arekkas, but wouldn't it make more sense to have the editor instance in the context (or via redux) instead of instantiating it somewhere outside your components (like currently)? And then, whenever an Editable is added, it gets the content via props `<Editable value={content} onChange={value => console.log(value)}` and it automatically binds to the editor instance (pulled from context) and adds the content to it? And as soon as it is unmounted, the content is removed from editor instance.

**Comment by arekkas** [comment]
A HOC or Provider Component are definitely good ideas. The primary reason for having an outside instantiator was that I wanted the layout editor to work outside of react (though still depending on react) - e.g. vue or something similar.

**Comment by davidpelayo** [comment]
@arekkas by the time I say that, I meant if there is a way to namespace a certain version of the bundle. This way you could build your assets containing more than 1 version of the same package

> Imagine you have your app on production running and you need to support a specific legacy version

in such specific case scenario.

**Comment by arekkas** [comment]
I didn't know that's possible. However, if you use a scoped package it will not be a problem to run two instances as it's two source files, two variables and thus two memory addresses which don't overlap.

**Comment by davidpelayo** [comment]
@arekkas I wouldn't make such assumptions. The lib itself ends up handling the DOM. Depending on how it's built and how it manages the DOM may collide or cause conflicts or not.

**Comment by arekkas** [comment]
That is not an assumption. It's a local variable scoped in a function and two of those functions exists. The local variables do not clash - otherwise javascript development would be impossible. If it's two files and not a global variable it's not the same thing.

```
// file1.js
(() => {
  const foo = 'foo'
  return foo
})()
```

```
// file2.js
(() => {
  const foo = 'bar'
  return foo
})()
```

```
// file3.js
file1() // 'foo'
file2() // 'bar'
```

**Comment by davidpelayo** [comment]
@arekkas I know what you mean. Right and fair enough. Probably, I didn't explain myself well enough.

I was meaning that when it comes to `file1.js` (version X) manipulating the DOM as well as `file2.js` (version Y) manipulating the DOM, depending on how file1 and file2 select elements across the DOM, etc., may cause conflicts. That's all.

**Comment by arekkas** [comment]
I see, in that case I wouldn't worry either as no DOM manipulation happens during `new Editor()`, only when using the react components such as `<Editable>`. So it's safe to run two versions here as well and if in fact there was an issue (there is none reported yet) it would not boil down to the singleton pattern of `new Editor()` :)
