### ISSUE TITLE
devices/touch: cannot move widgets around

### ISSUE THREAD

**Issue by ngreduce** [ory/editor#401]
Cannot move widgets in Chrome for Android.

**Comment by arekkas** [comment]
Hey, yes, mobile is currently not supported. The backend we use (react-dnd) has some support for dnd on mobile but I need to check that out in more details.

**Comment by sidati** [comment]
Hi @arekkas,
Its almost a year 😀, hope its planned now ??

**Comment by arekkas** [comment]
react-dnd removed their touch package, but it seems like there is a third party one available from yahoo: https://github.com/yahoo/react-dnd-touch-backend

Unfortunately I have very little time currently so I won't be able to check it out. If you want to give it a shot yourself, I'll try as best as I can to support you.

**Comment by arekkas** [comment]
Oh wait, it's actually even easier than that (I remember now that this was fixed)! We already implemented this functionality. You can pass your own dnd backend when initializing the [editor](https://github.com/ory/editor/blob/master/packages/core/src/index.js#L86) so just pass the yahoo one there and it should work!

See: https://github.com/ory/editor/issues/424

**Comment by sidati** [comment]
Nice approach 😀,
thanks
