### ISSUE TITLE
Add convenience function to get state of an editable from editor object

### ISSUE THREAD

**Issue by Discordius** [ory/editor#402]
It's currently pretty hard to get the state of an editable. You either have to query the store and use one of the existing selectors, or cash the current state on every call to `onChange`. We probably want to have a function along the lines of `editor.editables.getState({id: "example-id"})`, or something like that, to make querying a lot easier.

**Comment by arekkas** [comment]
How about something like `editor.query.editable('id')`?

**Comment by Discordius** [comment]
Yeah, that seems great to me. I like the idea of a query interface.
