### ISSUE TITLE
Editable still fires onChange event after <Editable /> component is gone

### ISSUE THREAD

**Issue by Discordius** [ory/editor#404]
I have a form that has an `<Editable />` component that I use to submit comments on my page. The render function looks like this: 

```

Class CommentEditor extends Component {

...

render() {
    const document = this.props.document;
    const addValues = this.context.addToAutofilledValues;

    const editor = this.props.editor;
    const setState = this.setState;

    const onChange = function(data) {
      addValues({
        content: data,
      });
      return data;
    };

    return (
      <div className="commentEditor">
        <Editable editor={editor} id={placeholderContent.id} onChange={onChange} />
        <Toolbar editor={editor} />
      </div>
    );
  }

}
```

The `addValues` function calls setState in a higher-level component. When the CommentEditor unmounts, the editable still exists, and makes calls to onChange, even though the component that onChange was modifying doesn't exist anymore. 

Editable should probably remove the editable from the editor on unmount, or there should at least be a convenience function along the lines of `editor.trigger.editables.remove(editableId)` that I could call from my own unmount function.

**Comment by arekkas** [comment]
The issue is not the state I think, but some DOM handlers which aren't cleaned up properly. I'll investigate

**Comment by parham2** [comment]
سلام دوستان من با گوشی موبایل دارم کار می‌کنم حساب ایمیل من هم مسدود شده لطفا
من را ببخشید موبایل من بسیار داغ شده و خاموش میشود قصدم بی احترامی نیست 
همه شما استادان من هستید و من کوچک شما عزیزان امیدوارم من را مورد ببخشش قرار بدهید

**Comment by arekkas** [comment]
Sorry, no arabic, google translate gives gibberish.
