### ISSUE TITLE
Control how Rows and Cells are rendered via Plugin

### ISSUE THREAD

**Issue by paulkoanui** [ory/editor#417]
Hello, I'm in search of some general guidance on Plugin development.  I'm new to react.js since falling in love with this project and I'm looking to integrate a customized version of reveal.js that I created a while back as two ORY Layout plugins. I'm noting reveal.js in this post because it presents a use case for ORY editor that I don't know how to solve.  At this time, I'm still getting oriented with where the line between react.js and ORY editor lies.

Reveal.js has a strict requirement for the DOM structure of slide decks. In order for it work, it needs to be `.reveal > .slides > section`.  The problem that I'm encountering is that the DOM produced by an ORY plugin gets wrapped in Row/Cell divs and this breaks the structure.

For use in ORY editor, I thought it made most sense to deliver this as two layout plugins: Deck and Slide
Deck would render `<div className="reveal"><div className="slides">{children}</div></div>`
Slide would render `<section>{children}</section>`

Deck would be initialized with a defaultPlugin of Slide and Slide with a defaultPlugin of Slate

To build up a slide deck, you would drag a Deck onto the page then nest one or more Slide plugins inside of the Deck.  From there you are free to use any other plugins to build up the content inside of each section.

However, after some thought, I believe that the simplest way to solve this is to be able to control, inside of the plugin definition:
1. how the layout system should render cells that contain the plugin
2. how the layout system should render child rows of the plugin

If that were possible, I could accomplish my task with only a single Deck Plugin that:
* instructs layout system to render all child Rows as `<section>` instead of `<div>`
* instructs layout system to render the Deck's parent Cell as a `<div className="reveal"><div className="slides">{content}</div></div>`

With a Deck plugin defined with the customizations above, I could drag it onto the page and any other plugin that I nested inside which creates a row would actually render as a `<section>` which translates to a slide in reveal.js!

Is this already possible?  Are there any limitations to this approach that I'm unaware of?  If not already possible, could those most familiar with this project offer insight on the best implementation path for this?  I'd be happy to implement and PR back.

Thanks for taking the time,
Paul

**Comment by arekkas** [comment]
Hey @paulkoanui thank you for checking out the ORY Editor! :) You seem to have a good understanding of the system already. Unfortunately, we can't have a custom renderer for cells because we need to do some stuff in the background, such as detecting drag & drop, detecting resize events, and so on. The only thing I can imagine at the moment is a Deck which has some manual slide positioning, so not the ORY Editor itself is responsible for moving Slides around, but the Deck plugin.

Let me know what you think.

**Comment by paulkoanui** [comment]
Hey @arekkas, thanks for your response! I understand what you're saying. Instead of exposing a custom renderer for cells, what about exposing a few additional properties that can be used by the existing rendering logic when rendering cells and rows? I hesitate to implement manual slide positioning within my component because I believe that ORY editor is already capable of doing this extremely well. The only thing required is a little more flexibility in how those DOM elements are rendered.  Below is a suggestion that I believe to be benign to the normal behavior of ORY editor.

```
<!--IDEAL DOM, obviously won't get ORY goodies but works within my use case's constraints-->

<!--DECK-->
<div class="reveal">
  <div class="slides">
    
    <!--SLIDE-->
    <section>..slate...</section>
  
  </div>
</div>


<!--All the ORY goodness none of the reveal.js :( -->

<!--DECK-->
<div class="ory-row ory-cell-inner">
  <div class="ory-cell ory-cell-sm-12 ory-cell-xs-12">
    <div class="ory-cell-inner">

      <div class="reveal">
        <div class="slides">
        
          <!--SLIDE-->
          <div class="ory-row ory-cell-inner">
            <div class="ory-cell ory-cell-sm-12 ory-cell-xs-12">
              <div class="ory-cell-inner ory-cell-leaf">
          
                <section>..slate...</section>
          
              </div>
            </div>
          </div>
          
        </div>
      </div>

    </div>
  </div>
</div>

<!--Best of Both Worlds?-->

<!--DECK-->
<div class="ory-row ory-cell-inner">
  <div class="ory-cell ory-cell-sm-12 ory-cell-xs-12 reveal">
    <div class="ory-cell-inner slides">
      
      <!--SLIDE-->
      <section class="ory-row ory-cell-inner">
        <div class="ory-cell ory-cell-sm-12 ory-cell-xs-12">
          <div class="ory-cell-inner ory-cell-leaf">
  
            ..slate...
          
          </div>
        </div>
      </section>
    
    </div>
  </div>
</div>

```
In the best of both worlds scenario, you could expose additional properties on the plugin such as:
```
  "cell": {           //singular because it relates to the cell containing the plugin
    "outer": {        //affects the element you give .ory-cell to
      "tag": "div",
      "classes": []   //classes defined here are added alongside ORY classes
    },
    "inner": {        //affects the element you give .ory-cell-inner to
      "tag": "div",
      "classes": []   //classes defined here are added alongside ORY classes
    }
  },
  "rows": {           //plural because it refers to the child rows of the plugin
    "tag": "div",
    "classes": []     //classes defined here are added alongside ORY classes
  }

```
If the above properties existed for customization, my Deck definition would include this to accomplish my goal:
```
  "cell": {           
    "outer": {
      "tag": "div",
      "classes": ["reveal"]     //i'd turn the cell into a reveal.js container with this class...
    },
    "inner": {        
      "tag": "div",
      "classes": ["slides"]     //...and this one.
    }
  },
  "rows": {           
    "tag": "section",           //i'd make the row render as a section
    "classes": []
  }

```
It seems like an enhancement such as this shouldn't interfere with anything and would expand the possibilities for the kinds of plugins you can develop for the editor.  What do you think?

Paul

**Comment by arekkas** [comment]
That's a cool idea! Unfortunately, this won't work with React :( The class names themselves are simply there to give you the chance to add some CSS or to identify in what level we are. However, the real work lies within the React Components themselves, which can not be replaced simply like this. They are the ones dealing with all the tough work for the user experience.

Is there maybe a react wrapper for reveal js that is capable of dealing with this?

**Comment by paulkoanui** [comment]
Hi, I wanted to close this issue and follow up with some notes.  In the end, I ended up modifying the slate plugins to allow specification of custom html that can be wrapped around the A) the entire Text plugin instance, B) the active "Block" or C) the active "Mark" D) some custom plugins like a "section" plugin which output a simple html <section> and can host "Text" instances.  

For the use case described in this thread, I needed a specific DOM structure and no ORY-specific tags in my output.  For that, I have a second transformation phase that locates ".ory-row.ory-cell-inner > .ory-cell > .ory-cell-inner" and unwraps the children to eliminate those nodes in the output. 

Thanks,
Paul
