### ISSUE TITLE
Confusing Documentation

### ISSUE THREAD

**Issue by humbleBeginner** [ory/editor#421]
The documentation lacks clarity and it is not yet completed.

**Comment by arekkas** [comment]
Could you be more specific? It would help fixing the issue!

**Comment by humbleBeginner** [comment]
@arekkas Renderer API to the last topic has no contents

**Comment by arekkas** [comment]
Ah yes the API docs are auto-generated and very incomplete

**Comment by arekkas** [comment]
I removed the API docs from gitbook for now and added a guide on the core plugin, feel free to check it out: https://ory.gitbooks.io/editor/content/packages/core.html#core-ory-editor-core

**Comment by kennylbj** [comment]
@arekkas 
It would be a great pleasure for me if you could complete the api doc especially the 'ory-editor-core' package.
I would like to customize my own ui controllers such as DisplayModeToggle and Toolbar, but lack of the knowledge of 'Editor' api.
