### ISSUE TITLE
Navbar 

### ISSUE THREAD

**Issue by benoj** [ory/editor#427]
Hi,

Just wondering if there is a plugin or some other  means of creating a navbar - similar to Ory Sites pages?

Thanks,

Ben

**Comment by arekkas** [comment]
Hey yes, you can check out the package ui which is an example implementation of the navbar. Unfortunately, this is not well documented yet, but it's possible!

**Comment by benoj** [comment]
Ah great! Have you got a link, struggling to find it :/

**Comment by arekkas** [comment]
sure: https://github.com/ory/editor/tree/master/packages/ui

**Comment by benoj** [comment]
Ah sorry I actually meant a navbar package for the client to create one similar to how the default pages created with the ory editor have a navbar at the top. But looks like there isn't a premade one? So will have to create - Would be really cool if you guys had a list of external ory packages available (similar to how [dashing](https://github.com/Shopify/dashing/wiki/Additional-Widgets)

**Comment by arekkas** [comment]
Ah yes that one is not open sourced at the moment, I'll check out dashing soon, thank you for the hint!
