### ISSUE TITLE
Nesting Editable inside Content/Layout

### ISSUE THREAD

**Issue by Morphexe** [ory/editor#428]
Hey, not sure if I am missing anything, but is there a way to nest Editable inside a Cell ? I want to have only one UI instance, so I can drag the same plugins across all the Editables.
I assume I should share my editor instance, but this brings a few problems:

I was able to nest it inside a cell via a content plugin, but then something odd shows up, first if I save the state using the onchange a StackOverflow goes by, I am not sure why, but it seems in the content plugin, onChange is being triggerd by the subscription to the store, although there is a  "this.previousState" it is never assigned anywhere in, adding the assignment manually after the check resolves the Overflow issue.

Now any idea how I should tackle this?

**Comment by Morphexe** [comment]
I actually found out a solution for this, the issue with nested editables is the "focus" action, so if we pass a property in the plugin definition saying if the "content plugin" should be focused it actually works great.

**Comment by arekkas** [comment]
Unfortunately nesting editables will lead to serious issues with the drag and drop logic and is strongly discouraged. Try working with layout plugins instead!

**Comment by Morphexe** [comment]
Layout plugins don't allow multiple drop zones, that was my "requisite" eitherway I made it work on my side perfectly with some source modifications, anyway, thansk for the feedback :D

**Comment by arekkas** [comment]
Would you mind sharing those? :)

**Comment by agustin107** [comment]
@Morphexe Can you share your solution for this?
