### ISSUE TITLE
Move things: give drop indicator a white border

### ISSUE THREAD

**Issue by inyono** [ory/editor#435]
so that the indicators are also visible on dark background

**Comment by arekkas** [comment]
the best way to solve it would be to take the inverted color of the background..but I don't think there's an easy way at the moment

**Comment by inyono** [comment]
I was more thinking about images and stuff where you don't easily get the background. But having both a white and black part, u should probably see it most of the time.

**Comment by arekkas** [comment]
You're right, it's probably an easy fix to a hard problem

**Comment by arekkas** [comment]
Actually, there's a css property for that: [mix-blend-mode](https://css-tricks.com/almanac/properties/m/mix-blend-mode/)
