### ISSUE TITLE
Refresh editables

### ISSUE THREAD

**Issue by idajimenez** [ory/editor#436]
Hi! Is there a way that I could refresh or change the editables in the Editor? 
My scenario is that the editor's content is changing after I choose an option. I keep on having the warning: "You have defined multiple instances of Editor, this could cause problems." when I change options.

**Comment by arekkas** [comment]
Could you share the code? You don't really need to propagate any changes manually, using `editor.trigger.editable.update(/*...*/)` (see example [here](https://github.com/ory/editor/blob/master/examples/src/index.js#L96) but replace add with update) you can update any editable :)

Make sure to only have one `new Editor()` in your code!

**Comment by idajimenez** [comment]
Here is my implementation.
```
export default class MainEditor extends React.Component {
  constructor(props) {
    super(props);

    this.editorState = this.props.editorContent || createEmptyState();
    this.editor = new Editor({
      plugins: this.props.plugins,
      editables: [...this.props.editorContent, createEmptyState()],
    })
    this.onClickSave = this.onClickSave.bind(this);
  }

  render() {
    const { editorContent } = this.props;
    
    return (
      <div>
        <Editable 
          editor={this.editor} 
          id={this.editorState[0].id}
          onChange={state => this.onHandleChange(state)}
        />

        <Trash editor={this.editor}/>
        <DisplayModeToggle editor={this.editor} onClickSave={this.onClickSave}/>
        <Toolbar editor={this.editor}/>
      </div>
    );
  }
}
```

Will try `editor.trigger.editable.update(/*...*/)` and I think because I put the `new Editor()` in the constructor causes multiple instance of the Editor.

Thanks!

**Comment by idajimenez** [comment]
I just tried it and moved `new Editor()` outside the class, and it worked. Thanks a lot!

**Comment by arekkas** [comment]
Perfect! I'm glad you got it working!
