### ISSUE TITLE
how to isolate a single "Text" plugin instance and wrap it with an arbitrary css class?

### ISSUE THREAD

**Issue by paulkoanui** [ory/editor#440]
Hello, I have a simple requirement -- I want to inject a className into the div that wraps the slate editor seen here: https://github.com/ory/editor/blob/master/packages/plugins/content/slate/src/Component/index.js#L74

In my copy of this file, I've changed that line to read:
`<div className={editorState.document.data.cssClasses}>`

I've added an ORY editor plugin that is added to the bottom toolbar when a "Text" plugin is active.  The plugin allows one to add one or more css class names and then press an "Update" button to perform a transform().apply() on editorState.  I'm saving this string to editorState.document.data.cssClasses.

This all works great for a single "Text" plugin.  When there are multiple "Text" plugins on the page, changing editorState.document.data.cssClasses will update all "Text" plugins.

Now, conceptually, this is how I would expect behavior to be since I'm modifying the document data (and I'm assuming a document represents all "Text" plugins on the page). I chose to save the data to that location because it looked like each instance of "Text" plugin had its own unique numeric key when looking at editorState.  Furthermore, when I inspect the generated DOM, it looks like the div I mentioned above is being duplicated for each instance of the Text plugin (since each instance sits in its own cell).

Basically, I'm a bit confused as to the proper way to accomplish this use case:
1. fresh editor is loaded (with a single "Text" plugin saying "Write here..." -- call this TextA)
2. user enters "Add" mode
3. user adds a second "Text" plugin to the page (call this TextB)
4. user enters "Edit" mode
5. user edits TextA to say "TEST A"
6. user edits TextB to say "TEST B"
7. user places cursor in TextA to bring up settings toolbar for TextA
8. user enters "style1" in the cssClasses textbox in the toolbar and presses update
9. TextA now has "style1" added to the div className referenced above
10. user places cursor in TextB to bring up settings toolbar for TextB
11. user enters "style2" in the cssClasses textbox in the toolbar and presses update
12. TextB now has "style2" added to the div className referenced above

Here's what's actually happening:
1. fresh editor is loaded (with a single "Text" plugin saying "Write here..." -- call this TextA)
2. user enters "Add" mode
3. user adds a second "Text" plugin to the page (call this TextB)
4. user enters "Edit" mode
5. user edits TextA to say "TEST A"
6. user edits TextB to say "TEST B"
7. user places cursor in TextA to bring up settings toolbar for TextA
8. user enters "style1" in the cssClasses textbox in the toolbar and presses update
9. TextA now has "style1" added to the div className referenced above
10. user places cursor in TextB to bring up settings toolbar for TextB
11. TextB is immediately redrawn upon focus and the div referenced above reads "style1"

What is your recommendation?

Thanks,
Paul

**Comment by arekkas** [comment]
Hm that is weird, `editorState.document.data.cssClasses` should not change for all text instances at once, only for the one which is updated. Is it possible that, for some reason, multiple cells have the same ID? You can check that by logging the `onChange` callback in `<Editor onChange=...>`.

**Comment by arekkas** [comment]
Could you also show how you handle the `cssClasses` update?

**Comment by paulkoanui** [comment]
Here is my plugin code to handle the cssClass update: https://gist.github.com/paulkoanui/0bcf840af39e3c1a72e432bc8fed74ff

in Component.js, 
I'm injecting the css class names here: https://gist.github.com/paulkoanui/0bcf840af39e3c1a72e432bc8fed74ff#file-component-js-L75


Here's a video of what I'm seeing: https://drive.google.com/file/d/0B_gV2WNeE-p5YjJRSXdrblVqalE/view

In that video, what you see in the console is logged here:
https://gist.github.com/paulkoanui/0bcf840af39e3c1a72e432bc8fed74ff#file-component-js-L34

Should there be a value for __ownerID?

**Comment by arekkas** [comment]
Oh ok I think I know what the issue is. The editorState is actually a slate state meaning that you should not mess with it. Instead, you could use another key (e.g. `cssClass`) in `state`, so e.g.:

```
    const {
      focused,
      readOnly,
      state: { editorState, cssClasses },
      // ...
} = this.props
```

**Comment by paulkoanui** [comment]
Cool, thanks for the tip!  I took your advice and it worked a charm.

**Comment by arekkas** [comment]
Perfect, I'm glad you got it working!

**Comment by paulkoanui** [comment]
I'm having one more issue on this topic.  Given your suggestion to add another key "cssClasses" to the state that will track my additional state, how do you serialize this? From looking at the slate plugin's reducer it seems like this should be happening automatically.  Any advice?

**Comment by arekkas** [comment]
yes this should happen automatically iirc

**Comment by paulkoanui** [comment]
Aloha,

I took your suggestion and it worked great.  I've been able to extend the functionality of the ory-editor very easily after getting my bearings.  Excellent project!

Thanks,
Paul
