### ISSUE TITLE
No serializer defined for mark of type

### ISSUE THREAD

**Issue by paulkoanui** [ory/editor#442]
I wrote a plugin to work with ory-editor-plugins-slate that i modeled after the emphasize plugin and is used to assign a custom color to a selection.  The plugin is functioning as expected and I have a serializer function defined in the plugin. However, I receive the message `No serializer defined for mark of type "COLORIZE/SPAN"` -- that's my constant COLOR value referenced below.

Why would the ory-editor-plugins-slate plugin not see the serializer function on my plugin.  The function looks like this

```
serialize = (object: { type: string, kind: string }, children: any[]) => {
    if (object.kind !== 'mark') {
      return
    }
    if (object.type === COLOR){
      return (
      <span style={{ color: object.data.toJSON().foreground.hex }}>
        {children}
      </span>
      )
    }
  }
```

**Comment by paulkoanui** [comment]
I've got things working again. Once I switched from explicitly passing defaultPlugins into slate() to adding my plugin instances directly where you instantiate all of the other slate plugins things worked.

**Comment by arekkas** [comment]
Glad you worked it out!
