### ISSUE TITLE
Custom DisplayModeToggle

### ISSUE THREAD

**Issue by idajimenez** [ory/editor#457]
Hi! I am planning to create a custom DisplayModeToggle.
What I would to know:
- Is there a way that I can still access the states of the editor with the custom DisplayModeToggle?
- How can I change the state from there? Is there a function that I can call to set content to focused or isEditMode?

Thank you very much in advance.

**Comment by arekkas** [comment]
> Is there a way that I can still access the states of the editor with the custom DisplayModeToggle?

Yes that is possible. First you must wrap your components with redux (see [example](https://github.com/ory/editor/blob/master/packages/ui/src/Provider/index.js)) and then you will need to use selectors and actions to update the modes (see [example](https://github.com/ory/editor/blob/master/packages/ui/src/DisplayModeToggle/ToggleEdit/index.js)).

A list of actions for that is [here](https://github.com/ory/editor/blob/master/packages/core/src/actions/display.js#L26-L46) and the selectors can be found [here](https://github.com/ory/editor/blob/master/packages/core/src/selector/display/index.js#L12-L36).

**Comment by idajimenez** [comment]
@arekkas I followed your instructions and successfully created custom DisplayModeToggle without any problem.
Thank you very much!

**Comment by arekkas** [comment]
Awesome, I'm glad that I could be of help!
