### ISSUE TITLE
content.plugin.serialize is not a function

### ISSUE THREAD

**Issue by idajimenez** [ory/editor#469]
Hi!

I have created a custom layout plugin and it's defaultPlugin is also custom. Whenever I insert it in editor this error shows up: `Uncaught TypeError: content.plugin.serialize is not a function`. How can I fix this error? 
Thank you

**Comment by arekkas** [comment]
Without looking at the code I can not tell you what is wrong

**Comment by idajimenez** [comment]
Here is the code for defaultPlugin:
```
import React from 'react'
import Text from './Text'
import Icon from 'material-ui/svg-icons/action/subject'

export const createInitialState = () => ({ textValue: 'Sample Text' });

export default {
  Component: Text,
  name: 'content/text',
  version: '0.0.1',
  IconComponent: <Icon />,
  text: 'Text',
  allowInlineNeighbours: true,  
  createInitialState: createInitialState
}

```

plugin config:
```
const plugins = {
  content: [Text, Button, Divider, Image, Spacer],
  layout: [
    Banner({ defaultPlugin: Text })
  ]
}
```

custome layout:
```
import React from 'react';
import { v4 } from 'uuid'
import Icon from 'material-ui/svg-icons/content/flag'
import type { ContentPlugin } from 'ory-editor-core/lib/service/plugin/classes'
import Banner from './Banner'

export default ({ defaultPlugin }: { defaultPlugin: ContentPlugin }) => ({
  Component: Banner,
  name: 'layout/banner',
  version: '0.0.1',
  text: 'Banner',
  IconComponent: <Icon />,

  createInitialChildren: () => ({
    id: v4(),
    rows: [
      {
        id: v4(),
        cells: [
          {
            content: {
              plugin: defaultPlugin,
              state: defaultPlugin.createInitialState()
            },
            id: v4()
          }
        ]
      }
    ]
  }),

  handleFocusNextHotKey: () => Promise.reject(),
  handleFocusPreviousHotKey: () => Promise.reject()
})

```

**Comment by arekkas** [comment]
The code from those looks fine. What about the other plugins, for example `Button`?

**Comment by hamavb** [comment]
Hello,

I had the same issue when creating custom plugins.

Usually, the **Editor** loop throw the passed plugins to instantiate them by calling new ContentPlugin/LayoutPlugin (both extends from Plugin Class) basing on their types.

But in case of a custom Layout plugin the createInitialChildren method returns an object with uninstantiated Content/Layout plugins (if any used), therefore some of the methods/properties are being missed (such as serialize, handleBlur...) 

To fix thise issue, two steps :

1* Import ContentPlugin a/or LayoutPlugin class from ory-editor-core package

`import { ContentPlugin, LayoutPlugin } from "ory-editor-core/lib/service/plugin/classes"`

2* instantiate used Content/Layout Plugins inside **createInitialChildren** (I use **Image** Plugin in my case)

`                
content: {
	plugin: new ContentPlugin(Image),
	state: {
		src: "https://static.pexels.com/photos/45201/kitty-cat-kitten-pet-45201.jpeg"
	}
},
`

Full Code of Layout Plugin sample looks like :

`
import React from 'react'
import {v4} from "uuid"
import Image from 'ory-editor-plugins-image'
import { ContentPlugin, LayoutPlugin } from "ory-editor-core/lib/service/plugin/classes"

export default {
    Component: ({children}) => <div> {children || null} </div>,
    name: 'plugin/test',
    version: '0.0.0',
    text: 'Layout Plugin test',
    IconComponent: <div />,
  
    createInitialChildren: () => ({
      id: v4(),
      rows: [
          {
            id: v4(),
            cells: [
                {
                content: {
                    plugin: **new ContentPlugin(Image),**
                    state: {
                        src: "https://static.pexels.com/photos/45201/kitty-cat-kitten-pet-45201.jpeg"
                    }
                },
                id: v4()
                }
            ]
        }
      ]
    }),
    handleFocusNextHotKey: () => Promise.reject(),
    handleFocusPreviousHotKey: () => Promise.reject()
}
`

**Comment by idajimenez** [comment]
@hamavb Thank you so much! It's now working.
