### ISSUE TITLE
plugins/slate: Lists in importFromHtml not working in Editable

### ISSUE THREAD

**Issue by Knorrke** [ory/editor#470]
When I use the `importFromHtml` option in slate in an `Editable`, list items are not displayed correctly. It works perfectly well, when using `HTMLRenderer` of the `ory-editor-renderer`

![grafik](https://user-images.githubusercontent.com/11499926/30755305-626ab416-9fc6-11e7-91e0-ec953ee08c51.png)

Code of App.js:
```
import React, { Component }from 'react'

import Editor, { Editable, createEmptyState } from 'ory-editor-core'
import 'ory-editor-core/lib/index.css'

import { HTMLRenderer } from 'ory-editor-renderer'

import { Trash, DisplayModeToggle, Toolbar } from 'ory-editor-ui'
import 'ory-editor-ui/lib/index.css'
import slate from 'ory-editor-plugins-slate'
import 'ory-editor-plugins-slate/lib/index.css'

require('react-tap-event-plugin')()

const plugins = {
    content: [slate()],
    layout: []
}

const content = {
    id: 1,
    cells: [{
        id: "3fde7b92-fbfe-4b2d-85b3-bad431939df6",
        size: 12,
        content: {
            plugin: {
                name: "ory/editor/core/content/slate",
            },
            state: {
                importFromHtml: "<ul><li>One</li><li>Two</li></ul>"
            }
        }
    }]
}

const editor = new Editor({
    plugins,
    editables: [content],
})

class App extends Component {
    render() {
        return (
            <div>
                <p>With Editable:</p>
                <Editable editor={editor} id={content.id}/>
                <hr />
                <p>With HTMLRenderer:</p>
                <HTMLRenderer state={content} plugins={plugins}/>
                <Trash editor={editor}/>
                <DisplayModeToggle editor={editor}/>
                <Toolbar editor={editor}/>
            </div>
        );
    }
}

export default App;
```

**Comment by arekkas** [comment]
Is it possible that that's a style issue?

**Comment by Knorrke** [comment]
I don't know, but the code above is from a clear reactjs app (i used create-react-app and only modified the App.js and added the necessary dependencies). So I don't think thats the issue here?

**Comment by arekkas** [comment]
You can inspect the DOM and if there's in fact no ul/li items it's a bug but from here it looks like a broken styles issue.

**Comment by Knorrke** [comment]
I'll check the example above again, because I didn't check it there, but in my original code there was an ul tag but with paragraph children instead of li.
I let you know about the example above

**Comment by Knorrke** [comment]
Checked it, the DOM structure is wrong in the `Editable` variant, but correct in `HTMLRenderer`.
`Editable` produces the following:
```
<ul data-key="4">
  <p data-key="6">
    <!-- react-empty: 16 -->
    <span data-key="0"><span data-offset-key="0-0">One</span></span>
  </p>
  <p data-key="8">
    <!-- react-empty: 20 -->
    <span data-key="2"><span data-offset-key="2-0">Two</span></span>
  </p>
</ul>
```

Whereas `HTMLRenderer` produces:
```
<ul>
  <li>One</li>
  <li>Two</li>
</ul>
```

**Comment by samuel-gaunt** [comment]
I am experiencing the same issue. It is also happening in the tech demo https://editor.ory.am/

**Comment by inyono** [comment]
Can confirm, the slate list plugin itself is broken, the import is probably fine.

**Comment by arekkas** [comment]
Maybe 0.8.0 resolves this: https://www.npmjs.com/package/slate-edit-list

**Comment by amalow** [comment]
Have there been any updates on this issue? If needed I can look at upgrades and put a PR up.
