### ISSUE TITLE
Consider binding mousetrap events to a specific element. 

### ISSUE THREAD

**Issue by samuel-gaunt** [ory/editor#474]
I am currently creating a web app that uses the ory editor inside a div with some other text fields around it. This has caused an issue where if you are in editMode and not currently focused on the ory editor, then pressing one of the keys bound in components/HotKey/Decorator.js causes the error below.

`Decorator.js:126 Uncaught TypeError: Cannot read property 'node' of null
    at remove (Decorator.js:126)
    at _fireCallback (mousetrap.js:616)
    at Mousetrap.self._handleKey (mousetrap.js:677)
    at Mousetrap../node_modules/mousetrap/mousetrap.js.Mousetrap.handleKey (mousetrap.js:994)
    at HTMLDocument._handleKeyEvent (mousetrap.js:737)`

I have been able to very badly fix the issue by unbinding the mousetrap events myself. But this is pretty dodgy and still leaves an issue where pressing 'ctrl+z' will undo changes in both the ory editor and the surrounding text fields.
`Mousetrap.unbind('backspace');`

Looking at the mousetrap [docs](https://craig.is/killing/mice) it looks like we might be able to bind the events to specific element. I understand this might be out of scope and that ory editor was not designed to be put in an interface with other inputs.

**Comment by arekkas** [comment]
Hi, sorry for the late reply. Where it makes sense I'd be open to bind mousetrap events to a local element. For undo/redo the question is where should that work? On the whole document or only when a specific element is focused?

**Comment by samuel-gaunt** [comment]
I should have updated this issue. I quickly realised after posting that binding to a specific element would not work as well. Similar to what you said, I have been able to bind the events with an onFocus on a div around the editor and unbind the events with onBlur.
