### ISSUE TITLE
handle on component when click on element of plugin.

### ISSUE THREAD

**Issue by nqthuan303** [ory/editor#475]
Hi, can someone help me. 
I want to handle click event on EditPage component when i click on "Edit Device" of IotDevice Plugin. Here is my code.

---EditPage component which is integrated ory editor---

---IotDevice Plugin----
`
return {
Component: Device,
IconComponent: ,
name: 'IotDevice',
version: '0.0.1',
text: 'IoT Device',
reducer: reducer
};
`
---Device component---

class Device extends Component {

    componentDidMount() {
        const {pluginActions, item} = this.props;
        pluginActions.onSubscribeTopic(item.topic);
    }

    onChange = (value) => {
        const {item, pluginActions} = this.props;
        pluginActions.onDeviceChange({topic: item.topic, value: value});
    }

    onClickEdit = () => {
        const {pluginActions} = this.props;
        pluginActions.onClickEdit(true)
    }

    render() {
        const {state: {
                deviceStatus
            }, isEditMode} = this.props;

        const {item, controlType} = this.props;

        const statusKey = item.topic;

        const deviceValue = (deviceStatus && deviceStatus[statusKey])
            ? deviceStatus[statusKey]
            : false;

        if (controlType == 'slider') {
            let sliderValue = isNaN(deviceValue)
                ? 0
                : Number(deviceValue);
            let sliderLowValue = isNaN(item.lowValue)
                ? 0
                : Number(item.lowValue);
            let sliderHightValue = isNaN(item.highValue)
                ? 0
                : Number(item.highValue);

            return (<AntdSlider
                step={0.1}
                value={sliderValue}
                onChange={this.onChange}
                tipFormatter={(value) => {
                return `${value} ${item.unit}`;
            }}
                min={sliderLowValue}
                max={sliderHightValue}
                defaultValue={24}/>);
        }

        if (controlType == 'value') {
            return (
                <div key={1} className="mqtt-child-value">
                    {deviceValue}
                </div>
            );
        }

        return (
            <div style={{position: 'relative'}}>
                {isEditMode
                    ? <a
                            style={{
                                position: 'absolute',
                                fontSize: '11px',
                                cursor: 'pointer',
                                textDecoration: 'none !important',
                                right: 0,
                                top: '-12px'
                            }}
                            onClick={this.onClickEdit}>Edit Device</a>
                    : null}
                <Switch
                    checked={deviceValue == 'true'}
                    defaultChecked={deviceValue == 'true'}
                    onChange={this.onChange}/>
            </div>

        );
    }
`
Thank all.

**Comment by nqthuan303** [comment]
and how can i use reducer in global app (not only in plugin) ?

**Comment by arekkas** [comment]
What is your problem exactly?

**Comment by nqthuan303** [comment]
i want to detect on component (this component will integrate ory editor) when i click on an element of component plugin.

**Comment by arekkas** [comment]
I'm still not sure exactly what you're trying to do. Do you want to detect in the plugin that wraps your react component that something has been clicked?

**Comment by nqthuan303** [comment]
i have EditPage component
i have IoTPlugin
i want to detect in EditPage component when i click on something of IoTPlugin's component

**Comment by arekkas** [comment]
And EditPage wraps the Editor component?

**Comment by nqthuan303** [comment]
yes, EditPage wraps ory editor

**Comment by arekkas** [comment]
I see, in that case, you will need a bit of trickery. The idea is to wrap the component inside the plugin creator:

```jsx
export default (callback) => {
  const Component = () => (
    <div onClick={callback} />
  )

  return {
    name: "foo",
    version: "bar",
    Component
  }
}
```

That way you can pass a callback when instantiating the plugin:

```
const callback = () => console.log('I was called')
const plugin = myPlugin(callback)
```

And can thus pass that callback also to your component.

Hope it helps

**Comment by nqthuan303** [comment]
thank you so much.

**Comment by arekkas** [comment]
Glad to be of help!
