### ISSUE TITLE
Inserting json

### ISSUE THREAD

**Issue by idajimenez** [ory/editor#486]
Hi! 
Is there an api call for inserting a json to another json? For example I have a json for header, I want to put that into a json for body. Another scenario is, there is a json that can be inserted even at the middle part of the body. Is that even possible? Thank you!

**Comment by arekkas** [comment]
Hi, is this still an issue for you? What type of JSON are you looking on inserting?

**Comment by idajimenez** [comment]
Hi! yes, the JSON that I will insert is also an editable.

**Comment by arekkas** [comment]
You can update the editor state with `editor.trigger.editable.add(yourEditableObject)`, but you can't merge two editables at the moment in a native way. One possibility to merge them, would be to combine the `cells` properties of both, so something like:

```
const editable1 = { /* ... */ }
const editable2 = { /* ... */ }

const mergedEditable = {
  ...editable1,
  cells: [ ...editable1.cells, ...editable2.cells ]
}
```

**Comment by idajimenez** [comment]
Thanks @arekkas!

**Comment by idajimenez** [comment]
Hi @arekkas, one more thing, is there a way to insert or push an object in the children of a layout plugin? Maybe calling it inside that layout component? Thanks!

**Comment by arekkas** [comment]
Hm, it is of course supported within the editor itself, but not really exposed via an API. One possibility would be to dispatch one of the `CELL_INSERT_{ABOVE|BELOW|LEFT_OF|...)` actions using `editor.store.dispatch()`, but you would have to have some knowledge of the internals such as the cell id.
