### ISSUE TITLE
HTMLrenderer custom props

### ISSUE THREAD

**Issue by bension10** [ory/editor#499]
How to pass props on HTMLRenderer and Editable?

`
<HTMLRenderer state={data} plugins={plugins} foo={bar} />
`
`<Editable editor={editor} id={content.id} onChange={this.handleEditorChange} {...this.props} />`

I'm aware on how to pass some data on a specif content plugin

`export default (store) => {`

  `const Component = (props) => (<SearchResult fields_data={store} {...props} />)`

  `return {`
    `Component,`
   ` IconComponent: <Subject />,`
    `name: 'moderator/content/search-result-field',`
   ` version: '0.0.1',`
   ` text: 'Search Result Field',`
 ` }`
`}`

but is there a way to pass my custom props and merge it to ory editor's store on HTMLRenderer and Editable?

**Comment by arekkas** [comment]
https://github.com/ory/editor/issues/443
