### ISSUE TITLE
Cant initialize without binding to an id

### ISSUE THREAD

**Issue by petter-kaspersen** [ory/editor#503]
Per the documentation it says  that you initialize an editor using
`ReactDOM.render((
  <Editable
    editor={editor}
    id="1"
    onChange={(editable) => {
      saveToBackend(editable)
    }}
  />
), document.getElementById('editable-1'))`

but my problem is that I'm using React with JSX, which means I instantiate my classes like this:

`export default class ComposeArticle extends React.Component {
  constructor(props) {
    super(props);
  }

  render(
      
  )
}
`
Is there a way to pass the id of the element i want to render to the <Editable /> component?

**Comment by arekkas** [comment]
It's a react component, you can use it within any react class.
