### ISSUE TITLE
Extending / Overriding ory-editor-plugins-slate 

### ISSUE THREAD

**Issue by X-Tender** [ory/editor#505]
Is it possible to extend the `ory-editor-plugins-slate` plugin or replace it with a modified one?
I would like to add a custom function to the texteditor.

**Comment by X-Tender** [comment]
I would like to add a function like the emojy example in slate.
http://slatejs.org/#/emojis
Or is it llready possible in ory editor to add text inline elements/plugins?

**Comment by arekkas** [comment]
> Is it possible to extend the ory-editor-plugins-slate plugin or replace it with a modified one?
I would like to add a custom function to the texteditor.

Extension is somewhat possible by registering new plugins for slate. Replacing it completely is definitely possible .)
