### ISSUE TITLE
React 16 & Material UI 1.0

### ISSUE THREAD

**Issue by mattblackdev** [ory/editor#511]
Hi, I'd like to get a pulse on the roadmap a little bit. I noticed a couple issues in the milestones mentioning material-ui@next. Right now they're on 1.0.0-beta.32 and my twitter senses suggest they are getting close to official release. In addition I'm curious about the level of effort it would be to upgrade this project to React v16. I'm sure it is significant but I haven't found any discussions on that here.

Point is, I am on a project at work where ORY would be a perfect fit in terms of features, mobile support and pluggable architecture. However, we can't go back to material-ui v0 or React 15. So, if it's feasible to contribute to a dependency upgrade, I'd be more than happy.

As a final note, I noticed a few comments about separating the material-ui stuff from core, which IMO is probably the smart thing to do, but it is certainly not trivial. In any case, another package we use at work is the [DevExtreme React Grid](https://devexpress.github.io/devextreme-reactive/react/grid/) project. I think it's one of the best examples of pluggable architecture out there.

**Comment by arekkas** [comment]
Hey! I'd be totally up for a PR. I'm also in favor of removing Material UI as a whole - it's just laziness and my inability to design good UIs which brought us to using MUI. Having said that, the current UI elements are considered a reference implementation for the plugins and the toolbar - but I understand that they could be seen as core to the library.

I don't think it would be a lot of work to get to React v16. MUI might be a different story, although I'd prefer to wait for stable v1.

What would really be needed is upgrading Slate - but that's a ton of work because Slate breaks BC with almost every minor.

**Comment by andreastoermer** [comment]
I use the ory editor in my project with React 16 and it works. I don't have any problems.

On topic of material ui, i forked this project to play a little bit with removing the code and at fabric ui as the base. when the moving out of core into a plugin part is done i will create a pr including a documentation of to create your own view plugin with the framework you love. but this operation needs time :D

**Comment by inyono** [comment]
Same here. React 16 works without problems (to be fair: we also don't use material-ui so that might lead to problems)

**Comment by HriBB** [comment]
I looked at the code a little bit. There's a lot :) In my use case, I tried to override `BottomToolbar` styles, but it's not possible ATM. It would be cool, if we could somehow control the components that get rendered. 

In any case, I can help with the Material UI 1.0 PR ;)

**Comment by warp** [comment]
@arekkas I am currently working on a PR to upgrade material-ui to 1.2.0 and react to 16 wip at https://github.com/ory/editor/pull/535 still needs style tweaks

**Comment by davidfurlong** [comment]
Any updates? Also @inyono what do you use at serlo? I can't find a public repo for it

**Comment by PeterKottas** [comment]
I believe this can be closed as the PR was merged in

**Comment by arekkas** [comment]
yes
