### ISSUE TITLE
Expose ContentPluginProps?

### ISSUE THREAD

**Issue by jtl3d** [ory/editor#516]
Hey, cool project! I'm just now starting to create some custom plugins, but I definitely feel I'm going about it awkwardly. I basically just copied code for an existing ory-editor-plugins component and have been trying to get it to run. One issue I found is the ContentPluginProps type is not accessible in ory-editor-core. Can that be exposed so I can import it?

Or am I going about this the wrong way?

**Comment by arekkas** [comment]
Hey, the `ContentPluginProps ` are just a type (in the context of flow). Importing them won't really do anything because we don't expose / compile types yet. Other than that, you're going at it the right way!

**Comment by jtl3d** [comment]
Ah, got it. I took out the part defining the argument type and that got me rolling again. Thanks for your help!

For starters I'm adding the option for an Image to be a link. I think I can probably throw together a pull request when I'm done.

**Comment by arekkas** [comment]
Awesome! :)
