### ISSUE TITLE
Question: where do plugins get loaded?

### ISSUE THREAD

**Issue by SirWindfield** [ory/editor#517]
I am trying to implement a plugin system aswell that enables users to extend my application with new functionality. I tried to take a look at the source code but couldn't find the LoC that actually load (aka `require`) the plugins. `PluginService` does offer methods for adding plugins but they seemed to be unused.

Sorry to polute your issue tracker with a question :)

**Comment by arekkas** [comment]
https://github.com/ory/editor/blob/master/examples/src/index.js#L60-L70
