### ISSUE TITLE
HTMLRenderer giving `document not defined` error on server side

### ISSUE THREAD

**Issue by rashid-aslam** [ory/editor#519]
`ReferenceError: document is not defined`

Error i'm getting while using HTMLRenderer on server side. I generated a small content in editor using slate plugin. When I pass on same editor state to HTMLRender with slate plugin then it gives me error.

HTMLRenderer can be used for server side rendering, What could be the wrong here?

**Comment by arekkas** [comment]
Which plugins do you use?

**Comment by rashid-aslam** [comment]
Just the `slate` plugin for pure textual content. 

Same is the case with `image` plugin. I have not tested `spacer` and `video` plugins yet

**Comment by arekkas** [comment]
Ok, that's weird. Which version are you on? The `document` bug typically comes from some plugin requiring access to that `document`, but it's not available due to SSR.

**Comment by rashid-aslam** [comment]
`"ory-editor": "^0.2.27"`

all plugins are also on same version. The `slate` plugin itself has this dependency `"slate": "^0.21.4"`

**Comment by arekkas** [comment]
Do you use any custom plugins?

**Comment by rashid-aslam** [comment]
I have made one just for demo. It renders fine on server side if rendered standalone. But this `slate` issue is standalone. No other plugin, just `slate`.

**Comment by rashid-aslam** [comment]
Here is the editor state I'm trying to render on server

`{"id":"6e6d5e82-2528-4f7c-b720-0180c11aa220","cells":[{"id":"83ae6f47-f6ab-40de-9079-409015233ae9","inline":null,"size":12,"content":{"plugin":{"name":"ory/editor/core/content/slate","version":"0.0.1"},"state":{"serialized":{"nodes":[{"kind":"block","type":"HEADINGS/HEADING-ONE","nodes":[{"kind":"text","text":"About Us"}],"data":{"align":"center"}},{"kind":"block","type":"PARAGRAPH/PARAGRAPH","nodes":[{"kind":"text","text":"Cms Page Content"}],"data":{"align":"center"}}]}}}}]}`

**Comment by rashid-aslam** [comment]
This is state is with my custom plugin only. It renders fine on server side.

`{"id":"8a9cceae-7c0e-4441-964f-ff0deef5f9aa","cells":[{"id":"b3a8e604-3d7d-4c8c-8e98-f5e5d17c3bb6","inline":null,"size":12,"rows":[{"id":"b96af995-8f56-4c3e-9a47-19917df47776","cells":[{"id":"5ac7a113-3f10-4ec8-9ff1-965263751c59","inline":null,"size":12,"content":{"plugin":{"name":"example/content/dynamic","version":"0.0.1"},"state":{"content":"I am dynamic content."}}}]}]}]}`

**Comment by arekkas** [comment]
Hm, that's really strange cause the slate plugin doesn't use the slate component for SSR but instead uses the [StaticComponent](https://github.com/ory/editor/blob/master/packages/plugins/content/slate/src/index.js#L119).

Can you tell me which line and file cause the error?

**Comment by rashid-aslam** [comment]
I can't really tell which line because I'm using production build from an app based on create-react-app. Development build has webpackdev server code and it also add some other errors.

What i see is this

`ReferenceError: document is not defined
    at Object. (V8Js::compileString():24:738359)
    at t (V8Js::compileString():24:101)
    at Object. (V8Js::compileString():24:730705)
    at t (V8Js::compileString():24:101)
    at Object. (V8Js::compileString():24:714317)
    at t (V8Js::compileString():24:101)
    at Object. (V8Js::compileString():24:120843)
    at t (V8Js::compileString():24:101)
    at Object. (V8Js::compileString():24:653766)
    at t (V8Js::compileString():24:101)`

I have found this by drilling down to enabling disabling the slate plugin on the HTMLRenderer.

**Comment by arekkas** [comment]
Shit, it's possible that a transient dependency (so a dependency of a dependency) introduced the document without checking if it's available, causing this bug. It will be a bit tricky to find the issue without a stack trace. I know it's difficult, but could you do some digging? My next days are packed with stuff so I don't have much time to get into it.

The way I would approach it is to add a bunch of `console.logs()` in the slate plugin (in the node_modules directory) and see which of the console logs is the last one that gets executed before the crash. That way, you can narrow it down and work your way towards finding the issue.

**Comment by rashid-aslam** [comment]
Thanks, I'll try to narrow down the issue for you.

**Comment by rashid-aslam** [comment]
after some effort i found the line that throws the error
`module.exports =  !!document.attachEvent && window !== document.parentWindow;`

This line is found in `/node_modules/slate/dist/slate.js` required by `ory-editor-plugins-slate` with     `"slate": "^0.21.4"`.

Actual installed version of slate is `"version": "0.21.6"`,

**Comment by arekkas** [comment]
Awesome find! So does it work with version 0.21.6 or 0.21.4?

**Comment by rashid-aslam** [comment]
I have yet to try the older version. I will let you know.

**Comment by rashid-aslam** [comment]
I tried the older versions of `slate` but the error persists because the line with document reference exists in older versions too. However, if I remove the document reference then rendering works.

**Comment by aeneasr** [comment]
This should be fixed because we upgraded slate
