### ISSUE TITLE
IE Support

### ISSUE THREAD

**Issue by miguel-orange** [ory/editor#522]
I really like what you guys are doing here. I usually dev on chrome, and check safari. My project breaks on IE11, I then went to your demo site on IE11 and it's the same deal :(

**Comment by arekkas** [comment]
IE support is not planned. It works on Edge

**Comment by arekkas** [comment]
I know, unfortunately we don't have the resources to support IE which itself is basically discontinued by Microsoft and will vanish over the next years. But it's of course encouraged to contribute IE support patches.
