### ISSUE TITLE
Unregular json output

### ISSUE THREAD

**Issue by ChrisMio** [ory/editor#523]
**First question:** Does the OryEditor ALWAYS produce a row > cell strukture or are other output structures intended?

 **Second question:** Is there somewhere a documentation about the json Output?

 **The Problem:**
 When tragging arround an image between several cells, it looks in the frontend always the same, but
 the json output is sometimes(!) different. It happens sometimes when we move it several times, so its hard to reproduce but happens.

 **Examples**
 In all 3 cases it looks the same in the frontend. but json output varies :

**1#**
https://pastebin.com/XQSKEvju

**2#**
https://pastebin.com/3DnQWZyE

**3#**
https://pastebin.com/Anx9xTCu

**Comment by arekkas** [comment]
Yes, the structure is always like that and no other structures are supported as of now.

What you’re experiencing is caused by where the cell is dropped. There is an optimizer which tries to keep the tree structure as flat as possible, causing different outputs depending on drop target.

The optimizer itself is not very well documented.

**Comment by ChrisMio** [comment]
@arekkas 
Thank you for your informations.
Any ideas if it is possible to switch off the "optimizer"?

We would preffer a stable and predictable json output, since we need to work with it further to transfer it to print for instance.

**Comment by arekkas** [comment]
@ChrisMio without the optimizer, the output will be extremely ugly and with very deep trees and many empty nodes. What you're experiencing is (as far as I can tell) related to where the drop position of the element is. It depends on what the "parent" element that triggers the drop event is. Depending on that, the drop position in the JSON tree is decided. The optimizer simply removes garbage from the tree by joining empty nodes.

**Comment by ChrisMio** [comment]
@arekkas 
so, since you are saying it should be always a row>cell structure, it seems to be a bug that its possible to create an json output with a cell in the "root" outside of a row, did i understand this right?

if its caused by the optimizer, i would preffer a ugly but stable output that i can work with.
currently its diffcult for us , when the json output for the same visual arrangement may change. so is it possible to switch the optimizer of and have and ugly but predictable output?

**Comment by arekkas** [comment]
> so, since you are saying it should be always a row>cell structure, it seems to be a bug that its possible to create an json output with a cell in the "root" outside of a row, did i understand this right?

No, that is not possible. The root element is always a cell.

> if its caused by the optimizer, i would preffer a ugly but stable output that i can work with.
currently its diffcult for us , when the json output for the same visual arrangement may change. so is it possible to switch the optimizer of and have and ugly but predictable output?

The output is stable, but as you move things around they get inserted in different places which might cause different "internal" models of the document.

> the  whole thing is, we need to use the json output to generate PDF's. ..so  we have backend magic that tries to parse the json from ory and render  it. Its difficult when sometimes something is in a row and sometimes  not, and we need to re-create the layout that someone setup with ory  editor.

I don't really know how to help here, did you look at the layout model that we use (flexboxgrid)? Can't you reproduce just that using PDF?
