### ISSUE TITLE
Docs - update API code links

### ISSUE THREAD

**Issue by alexbrbr** [ory/editor#524]
The api docs readme (https://github.com/ory/editor/edit/master/docs/api/core.md) are pointing to an old commit (d780f8a2764165ebdadbec36260fae4d036c27c3, a year ago).

I was checking the findLayoutPlugin method and expected an error to be thrown but the behavior has changed in between. I am ok to update the docs , but not sure how.
Which solution do you prefer : 
1) point to master and remove the lines so people can look the method when they need
2) point to master, update the lines as they are now and hope changes will be updated in docs
3) point to the last commit and update the lines. it will need to be updated again to a new commit when implementation changes

I prefer solution 1 but I'd be happy to implement any of those if there's a solution you agree with.

**Comment by arekkas** [comment]
The docs are autogenerated so it's probably caused by that. There's [a command](https://github.com/ory/editor/blob/master/package.json#L47) which should update those lines!

**Comment by alexbrbr** [comment]
Thanks for your answer (my bad I did not see the autogeneration comment on top of the files).
I ran the command on my fork but it points the example on my fork instead of https://github.com/ory/editor (see https://github.com/ory/editor/pull/525).

Can you either run `NODE_ENV=development npm run docs:api` and update the docs or give me the ability to push new branches on the ory editor repo ?
I guess it would be even better to run the `npm run docs:api` on prepublish or on a precommit hook ?!

**Comment by arekkas** [comment]
> I guess it would be even better to run the npm run docs:api on prepublish or on a precommit hook ?!

Totally overlooked that, yes that would make a ton of sense! Would you mind creating a PR for that? :)

**Comment by alexbrbr** [comment]
Thanks for the  update !
I'll try to work on a clean solution to do this next week :)
