### ISSUE TITLE
React 16.4.0 breaks ory-editor-ui Buttons and some configs of 16.3.2 as well

### ISSUE THREAD

**Issue by davidfurlong** [ory/editor#537]
Ory-editor-ui (and some plugins) doesn't work on react 16.4.0 - react-tap-event-plugin isn't compatible (https://github.com/zilverline/react-tap-event-plugin/issues/121) and since material-ui depends on react-tap-event-plugin, buttons stop working

**Comment by arekkas** [comment]
This will hopefully be resolved with #535

**Comment by davidfurlong** [comment]
cheers

**Comment by davidfurlong** [comment]
Somehow I have broken ory-editor-ui buttons in React 16.3.2. Also that PR is getting stale.. I would contribute to that package, but we use ant design & I don't know material-ui & It would make more sense for us to build a fork of the repo with ant design & the priority is much too low for us to do that :(

**Comment by davidfurlong** [comment]
Are there any updates on a timeline for ORY-sites @arekkas ?

**Comment by boyandimitrov** [comment]
Which is the last react supported version by ory-editor at the moment?

**Comment by arekkas** [comment]
There is a huge PR ( #547 ) which will fix this, expect it to land in the next week.

**Comment by logankoester** [comment]
Thanks @arekkas, great to hear there is a timeframe on that PR.

**Comment by PeterKottas** [comment]
This can be closed now.
