### ISSUE TITLE
Customizing the drag-drop UI/UX

### ISSUE THREAD

**Issue by sebastienfi** [ory/editor#541]
Hi @arekkas 
First of all, thank you for the library. It is enjoyable to build pages using this tools.
I would like to customize the drag-drop experience.
I am facing a couple problems and I am hoping that you may help me get in the right direction.

1. How to deactivate drag-drop **for cells**? **I only need to drag-drop rows** to reorganize top to bottom the plugins added on a page. I don't need to be able to drag-drop content within a row. I also don't need to reorganize content left to right.

2. How to **configure offsets**? Actually, the dropTarget will activate only once very close to the extremity, I would like to activate the above target within 50% of the height, and the target below within the next 50% of height.

3. How to **replace the drag icon by the item being dragged** itself?

4. How to **customize the drop target**? I am looking to make the drop target pseudo-element mimic the height of the dragged element.

If this is not possible, I might need to deactivate the whole drag-drop of content and create my own. I may do this at plugin level.

**Comment by arekkas** [comment]
> How to deactivate drag-drop for cells? I only need to drag-drop rows to reorganize top to bottom the plugins added on a page. I don't need to be able to drag-drop content within a row. I also don't need to reorganize content left to right.

Not possible, unfortunately. I'm also not sure if it makes sense to include this functionality in the project as the idea of it is to be able to rearrange, add, and remove cells/plugins.

> How to configure offsets? Actually, the dropTarget will activate only once very close to the extremity, I would like to activate the above target within 50% of the height, and the target below within the next 50% of height.

Not sure if I understand you correctly, but there is a [matrix](https://github.com/ory/editor/blob/master/packages/core/src/service/hover/index.js#L99) which defines what action is triggered (hover above, hover below, hover left, ...) depending on the location of the cursor. The HoverService is currently not exposed/configurable but this could be fixed.

> How to replace the drag icon by the item being dragged itself?

Not possible at the moment, could be fixed though. A plugin could probably expose a config `dragIcon` which sets this.

> How to customize the drop target? I am looking to make the drop target pseudo-element mimic the height of the dragged element.

This is also currently not implemented, I think it could be possible to fix it but I would have to look into it in detail. A plugin could probably expose a config `dropTargetHeight` which sets this.

**Comment by sebastienfi** [comment]
Thank you @arekkas for your answers.
We implemented our own drag-drop solution without entering "Move things mode" but still using ORY internal API to rearrange the data.

Closing this now.
