### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by PeterKottas** [ory/editor#544]
Did anybody think/experiment/work with Localized texts using ory editor? While the format data is stored in is a serializable tree structure (according to docs) I don't see an easy way to maintain layout while making the texts translatable. (obviously I could just keep copies of the whole state with different texts in different languages but that sort of beats the purpose of having reusable layout in the first place). Are there any recommendations for this?

**Comment by arekkas** [comment]
There are currently no recommendations for translating content. You could maybe write a plugin that shows content based on browser language.

**Comment by PeterKottas** [comment]
Thanks for getting back to me. That's what I was afraid of. Custom plugin is probably the only way then. Would be complicated though. Doesn't make much sense to keep content from all languages in the state I guess so it would have to be returned from back-end conditionally based on some ID. Something to think about. Weird though, 7k stars, I would have though somebody before me encountered this requirement before.

**Comment by arekkas** [comment]
Typically translations aren't 1:1 so layouts aren't 1:1 either. That's probably why no one has come up with this requirement before.

**Comment by aeneasr** [comment]
IMO, translating content is out of scope for this repository. Closing - feel free to add ideas though if you see this differently.
