### ISSUE TITLE
Future of ory editor

### ISSUE THREAD

**Issue by PeterKottas** [ory/editor#545]
First of all, I am pretty sure this doesn't belong in issues. Would make more sense to discuss it on other channels but since I am not aware of your preference (slack or any of the other million options :) ) I'll try my luck here. 

After playing around with a lot of editors for react in last few months, I certainly must say the visual quality, approach to the problem and the general feel of the ory ui surpassed all of them. 

However as the choice of the right tool is very important for us, I just have a few questions that could help me understand what to expect from this lib in the future. 

1.  Is this actively developed? I know the amount of work that went into this is huge and I admire it. But at the moment, last release happened more than 6 months ago and with open source, that scares me a bit. 
2. Currently the lib relies on 2 huge libs, material-ui and redux. While the end result is great and the reasons for going this way are obvious (read a comment somewhere by one of you guys, that mui was chosen because you couldn't be bothered creating nice UIs, can very much understand that myself :D ) it still feels a bit too much overhead for a widely used lib. Are there any plans to maybe dropping them or making them optional? Especially the UI layer. Plus it would be great to see the redux implemented in a way where you doesn't have to create extra store for this lib. I know it made sense for you to keep it simple this way. But imagine every lib took this approach. You would have store for oidc, store for toastr and who knows what else. Usually these libs just expose a reducer, and allow you to inject your store into them to be used. I've seen some partial comments here and there about improving this but is there any actual work being done on this?
3. Localization as per my #544 seems like an important feature in today's multicultural world. We might actually choose to implement this and open sourcing if we go with ory.
4. React native support as per my #528 once again, imho a highly desired feature as most of the world use mobile these days. 
5. The lib currently doesn't work with latest react which once again looks scary to a person "outside" of this lib. The PR by @warp appears to be abandoned for more than a month. Is there any effort going on to fix this?

Lastly, I personally have a few libs of my own. Not even slightly as popular as this, but it already opened my eyes to the amount of work that goes into this. That's why I want to make sure it's well understood that all of what I've written wasn't meant as critique in any way. The lib is already great and used by many, I would just love to take a well informed decision that will work well for us in the future. Hope you understand and I'll be thankful for any input I can get on this.

**Comment by PeterKottas** [comment]
Btw, I've seen this https://github.com/ory/editor/milestones which seems promising but again not updated for a while. Just trying to say I made some research before posting this :)

**Comment by arekkas** [comment]
> Is this actively developed? I know the amount of work that went into this is huge and I admire it. But at the moment, last release happened more than 6 months ago and with open source, that scares me a bit.

Yes, but not by me. Instead, I review & accept contributions by the community and the adopters that rely on this system.

> Currently the lib relies on 2 huge libs, material-ui and redux. 

Redux does [not fit the definition](https://github.com/reduxjs/redux/tree/master/src) of a huge library at all. Material-ui is only used in the plugins and default ui. If you want, you can use the core instead and not rely on material-ui at all, but then you have to implement that stuff yourself.

> Localization as per my #544 seems like an important feature in today's multicultural world. We might actually choose to implement this and open sourcing if we go with ory.

That would be great! As with all contributions, they must be aligned with the product & API vision so please discuss your ideas before working on a huge PR.

> React native support as per my #528 once again, imho a highly desired feature as most of the world use mobile these days.

Not on our roadmap, hard to implement, but again feel free to discuss ideas for a PR.

> The lib currently doesn't work with latest react which once again looks scary to a person "outside" of this lib. The PR by @warp appears to be abandoned for more than a month. Is there any effort going on to fix this?

I was waiting for #535 but the author just commented that he won't be putting any more work into it. Feel free to make a new PR based on #535 that resolves the remaining issues.

> Lastly, I personally have a few libs of my own. Not even slightly as popular as this, but it already opened my eyes to the amount of work that goes into this. That's why I want to make sure it's well understood that all of what I've written wasn't meant as critique in any way. The lib is already great and used by many, I would just love to take a well informed decision that will work well for us in the future. Hope you understand and I'll be thankful for any input I can get on this.

This took me two years with several rewrites. Feel free to fork it and improve it to your needs. It will be much less work than writing your own.

**Comment by PeterKottas** [comment]
Thanks for the detailed info. I would have loved to hear you are going to personally develop this further, but obviously replying frequently and accepting contributions is second best thing. I'll be sure to get in touch before implementing any big changes. 

Also if you don't mind, one extra question popped in. 
Do you have any complete list of plugins that is maintained somewhere? Once again, given the great success you have here on github, I would have expected to seen quite a few of these. Is it that maybe people are not open sourcing what they come up with? (obviously you might not know, just thinking out loud)

**Comment by arekkas** [comment]
> Also if you don't mind, one extra question popped in.
Do you have any complete list of plugins that is maintained somewhere? Once again, given the great success you have here on github, I would have expected to seen quite a few of these. Is it that maybe people are not open sourcing what they come up with? (obviously you might not know, just thinking out loud)

Plugins definitely exist, I don't have a list though. Most people use this for web agency work and don't open source their changes, which is a shame.

**Comment by PeterKottas** [comment]
Yep agreed, we have an in-house product so no problem with open sourcing stuff. Ok thanks for the help here, I think I got what I needed and will be closing this.

**Comment by arekkas** [comment]
No problem
