### ISSUE TITLE
Set default mode

### ISSUE THREAD

**Issue by PeterKottas** [ory/editor#550]
Am I nuts or is not possible to set default mode at the moment? I would prefer to start with edit mode rather than preview. Happy to implement the change if need be but first I'd like to see if there's a way to do it at the moment.

**Comment by Knorrke** [comment]
I used `editor.trigger.mode.edit()` for this

**Comment by PeterKottas** [comment]
Beautiful, thank you very much @Knorrke ! Just out of curiosity, is this documented somewhere? Or did you have to look into the code?

**Comment by Knorrke** [comment]
Glad it helped :-) I think it was mentioned in some issue before, but not sure. It's not documented as far as I know, but all the actions available through `editor.trigger` can be found here: https://github.com/ory/editor/blob/af93e462d6057b878bc9495764a9b4e0a51e7856/packages/core/src/actions/index.js#L68-L114

Some usefull stuff there :-)

**Comment by PeterKottas** [comment]
Thanks that's indeed very useful!
