### ISSUE TITLE
Upgrade slate to latest version

### ISSUE THREAD

**Issue by PeterKottas** [ory/editor#553]
Hi, this is an issue I am reporting while working on this in case anybody want to contribute anything. I've noticed some warnings that has to do with slate being a rly old version. I wanted to upgrade it (which I though would be straight forward) but it opened whole can of worms as they've changed almost the entire api. After a few hours on this, it seems that the best solution (that doesn't include breaking changes) would be to create brand new slate-next content plugin that would use latest slate. Is this something that would make sense to you? In the meantime I am trying my best to just upgrade and keep it backward compatible but I am struggling. 
In particular, the plugin system changed, and I am not exactly sure how it worked before. The serialize and deserialize on every plugin doesn't make much sense to me at the moment.

**Comment by arekkas** [comment]
Yeah good point - keeping up with slate's changes has been challenging and a lot of breaking changes were introduced. The goal should be to keep the document model somewhat similar. A big breaking change will be upgrading the undo/redo. As long as the document model from the current slate version is compatible (or convertible) to the new one, we should avoid creating slate-next. I can probably find some time to look into this in next week or the week after. Not sure if @inyono has upgraded the slate version and has insights to share?

**Comment by arekkas** [comment]
Oh right, the plugins will probably break. I think that is a breaking change we can live with. What should not be breaking is existing documents!
