### ISSUE TITLE
Error when initializing

### ISSUE THREAD

**Issue by richtera** [ory/editor#559]
![image](https://user-images.githubusercontent.com/708186/44047742-4ed921b2-9efd-11e8-8859-5808b243f1dc.png)
Probably not a huge deal, but this is a react proptypes conflict.

**Comment by PeterKottas** [comment]
This will be fixed by #554 We are now working hard on merging this. The reason for the warning is ory-editor currently uses an older version of slate which has this problem. It's not a big deal though.
