### ISSUE TITLE
Best way to store state data

### ISSUE THREAD

**Issue by PeterKottas** [ory/editor#572]
Hi @arekkas , sorry this is not a real issue, just looking for information. Ory apparently have lot of data and I was just curious how you store it all, or what the best way would be. So far, I see 2 main options:

1. Store it as string in the database (probably preferable NoSql but Sql would do just fine I guess)
2. Keep the data in json format on web (probably s3/ azure storage or equivalents) and keep only the path to the data in the db

Now technically, second option is imho far superior (but would require more effort), I was just curious how you did it cause you obviously have plenty of data == plenty of experience with this. Thanks

**Comment by arekkas** [comment]
Both option are fine. One project that uses the editor (currently in staging) stores it as JSON in a SQL column. Not sure how fast S3 retrieval is, the JSON is usually also not extremely large (in terms of kb).

**Comment by PeterKottas** [comment]
Cheers man, S3 should be quite fast, you can basically use it as global cdn. (Netflix uses it for streaming quite a lot) I think overall it can keep the server lighter on ram to store json elsewhere but the fact that you can use db keeps me happy to follow the same approach. If we grow too big, we'll easily be able to solve it some other way.

**Comment by arekkas** [comment]
> If we grow too big, we'll easily be able to solve it some other way.

Always the case :)
