### ISSUE TITLE
Delete not working in demo

### ISSUE THREAD

**Issue by FraMecca** [ory/editor#594]
Whenever I press over an image or a video in teh demo editor, pressing DEL or Backspace does nothing.
This means that whenever I add an object I can remove it only with ctrl-z
Using Firefox 60.0

**Comment by aeneasr** [comment]
It's possible that, for some reason, the key is not properly intercepted. Might have to do with the lastest mui updates? ping @PeterKottas

**Comment by PeterKottas** [comment]
Did it ever work that way? Yeah of course when you press delete in empty slate editor, it removes it but I don't think I ever seen this working with images or video. You can still go to move and move it to trash though.

**Comment by aeneasr** [comment]
Oh yeah, I think I misread, I thought pressing DEL or Backspace did in fact delete the plugin. In that case, this is expected behavior!
