### ISSUE TITLE
State of the project

### ISSUE THREAD

**Issue by kosirm** [ory/editor#596]
Hi, sorry for using issues as a forum tool... I don't know how to reach you. Found this site, (https://www.ory.sh/sites/) which I believe it is ory editor based and part of ory products. Links on this site are dead or misleading (registration doesn't work, the download doesn't work, nobody respond to chat message, etc). So, quite a disappointment...
On the other hand, I think that this project (ory editor) is really interesting and I would like to use it (even contribute). Can anyone shed some light on this? What is the state of this project?

**Comment by aeneasr** [comment]
Hi there! We're not working on the ory sites project itself (website will be deprecated soon), but this one is being actively maintained with some great contributions.

We tried to hook this editor up with different static site generators, but it was a lot of work (back then) with an unclear path to monetization and a difficult market environment - which is the reason for discontinuation of that project (ORY Sites). I'm sure though, that the state of tooling is better today and that you could probably achieve that for your own project based on this editor.

Hope that answers your questions!

**Comment by kosirm** [comment]
Thank you for a prompt and clear reply! I totally agree with you, there are so many ssg's today... It would be interesting to see how ORY could be paired with Gatsby, because they are both react based. In the meantime I also found your [reply](https://github.com/ory/editor/issues/396#issuecomment-359235066) on #396. I would be really interested to know how ORY on top of NetlifyCMS is going on, if it is still in development. Anyway, ORY Editor with a [great api](https://github.com/ory/editor/blob/master/docs/api/core.md) is a fantastic project and I look forward to learn it better. Congrats!

**Comment by aeneasr** [comment]
I tried coupling Gatsby with this editor for a while about ~14 months ago, it was quite difficult back then but I think it has improved. Maybe @inyono can share some insights on the Netlify integration. In the meanwhile, I'm closing this issue but feel free to continue the discussion!
