### ISSUE TITLE
Slate deprecation warning

### ISSUE THREAD

**Issue by davidfurlong** [ory/editor#598]
Since the newest 0.4.4 versions of the ory slate plugin, my console is showing ```Deprecation (0.37.0): The `range.startKey` property has been deprecated, use `range.start.key` instead.``` in  slate-dev-logger.es.js

**Comment by PeterKottas** [comment]
This is tracked here #571 . Unfortunately that warning doesn't come from our code but from the list plugin. They have a PR going in to fix that. Haven't checked for a while though.

**Comment by aeneasr** [comment]
Right, thanks!
